FILE_LIST:=\
	../common/fence/fence_pkg.sv \
	../common/instructions.sv \
	../common/branch_compare/branch_compare_pkg.sv \
	../common/csr/csr_pkg.sv \
	../common/exec_unit/exec_unit_pkg.sv \
	../common/imm_gen/imm_gen_pkg.sv \
	../common/mem/mem_pkg.sv \
	../common/reg_file/reg_file_pkg.sv \
	../common/write_back/write_back_pkg.sv \
	../common/branch_compare/branch_compare.sv \
	../common/csr/csr.sv \
	../common/exec_unit/exec_unit.sv \
	../common/fetch/fetch.sv \
	../common/imm_gen/imm_gen.sv \
	../common/mem/mem.sv \
	../common/reg_file/reg_file.sv \
	../common/write_back/write_back.sv \
	../common/decode/decode_branch_compare.sv \
	../common/decode/decode_csr.sv \
	../common/decode/decode_exec_unit.sv \
	../common/decode/decode_imm_gen.sv \
	../common/decode/decode_mem.sv \
	../common/decode/decode_pc_input_select.sv \
	../common/decode/decode_reg_file.sv \
	../common/decode/decode_write_back.sv \
	decode/decode.sv \
	core.sv

INCLUDE_DIRS:=\
	-I. \
	-I../common

OUTPUT_NAME:=core
TOPMODULE:=core

include ../Makefile

