FILE_LIST:=\
	mem.v \
	fetch.v \
	decode_D.v \
	decode_X.v \
	decode_M.v \
	decode_W.v \
	imm_gen.v \
	reg_file.v \
	branch_compare.v \
	exec_unit.v \
	write_back.v \
	core.v

INCLUDE_DIRS:=\
	-I.

OUTPUT_NAME:=core
TOPMODULE:=core

include ../Makefile

