FILE_LIST:=\
	../components/mem/mem.v \
	../components/fetch/fetch.v \
	../components/decode/decode_D.v \
	../components/decode/decode_X.v \
	../components/decode/decode_M.v \
	../components/decode/decode_W.v \
	../components/imm_gen/imm_gen.v \
	../components/reg_file/reg_file.v \
	../components/branch_compare/branch_compare.v \
	../components/exec_unit/exec_unit.v \
	../components/write_back/write_back.v \
	core.v

INCLUDE_DIRS:=\
	-I. \
	-I../components/mem \
	-I../components/fetch \
	-I../components/decode \
	-I../components/imm_gen \
	-I../components/reg_file \
	-I../components/branch_compare \
	-I../components/exec_unit \
	-I../components/write_back

OUTPUT_NAME:=core
TOPMODULE:=core

include ../Makefile

